from app.models.base import Base
from app.models.company import Company, CompanyPage, CompanySource
from app.models.discovery import DiscoveryRun, SearchQuery, SearchResult
from app.models.enums import (
    CompanyStatus,
    ConfidenceLevel,
    ContradictionStatus,
    CrawlStatus,
    EpistemicStatus,
    EvidenceType,
    Freshness,
    ObservationState,
    OpportunityStatus,
    PageType,
    ResearchSourceType,
    ResearchStage,
    ResearchStatus,
    RetrievalStatus,
    RunStatus,
    SourceReliability,
    SourceType,
    VerificationStatus,
)
from app.models.intelligence import (
    DecisionMaker,
    Opportunity,
    OpportunityEvidence,
    OpportunitySignal,
    Signal,
    SignalEvidence,
    UbmCapability,
)
from app.models.outreach import (
    AuditEvent,
    GmailConnection,
    Outreach,
    OutreachCampaign,
    OutreachClaim,
    OutreachClaimEvidence,
    OutreachOutcome,
    OutreachVersion,
    SenderProfile,
)
from app.models.research import (
    Contradiction,
    Evidence,
    ResearchBrief,
    ResearchRun,
    ResearchSource,
)
from app.models.target import Target

__all__ = [
    "Base",
    "Target",
    "DiscoveryRun",
    "SearchQuery",
    "SearchResult",
    "Company",
    "CompanySource",
    "CompanyPage",
    "RunStatus",
    "CompanyStatus",
    "SourceType",
    "PageType",
    "CrawlStatus",
    # --- phase 2 ---
    "ResearchRun",
    "ResearchSource",
    "Evidence",
    "Contradiction",
    "ResearchBrief",
    "Signal",
    "SignalEvidence",
    "UbmCapability",
    "Opportunity",
    "OpportunityEvidence",
    "OpportunitySignal",
    "DecisionMaker",
    "ResearchStatus",
    "ResearchStage",
    "ResearchSourceType",
    "RetrievalStatus",
    "SourceReliability",
    "EvidenceType",
    "EpistemicStatus",
    "Freshness",
    "ConfidenceLevel",
    "ObservationState",
    "OpportunityStatus",
    "ContradictionStatus",
    "VerificationStatus",
    # --- phase 3 ---
    "SenderProfile",
    "OutreachCampaign",
    "Outreach",
    "OutreachVersion",
    "OutreachClaim",
    "OutreachClaimEvidence",
    "OutreachOutcome",
    "GmailConnection",
    "AuditEvent",
]
