"""phase 3: outreach, versions, claims, campaigns, gmail, audit

Revision ID: 6db10e97d6bc
Revises: 7c339ba92a9e
Create Date: 2026-09-20 12:13:41.806620
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '6db10e97d6bc'
down_revision = '7c339ba92a9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=160), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_object_id'), 'audit_events', ['object_id'], unique=False)
    op.create_index(op.f('ix_audit_events_object_type'), 'audit_events', ['object_type'], unique=False)
    op.create_index('ix_audit_object', 'audit_events', ['object_type', 'object_id'], unique=False)
    op.create_table('gmail_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_email')
    )
    op.create_index(op.f('ix_gmail_connections_created_at'), 'gmail_connections', ['created_at'], unique=False)
    op.create_index(op.f('ix_gmail_connections_is_active'), 'gmail_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_gmail_connections_status'), 'gmail_connections', ['status'], unique=False)
    op.create_table('sender_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=160), nullable=True),
    sa.Column('company', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sender_profiles_created_at'), 'sender_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_sender_profiles_is_default'), 'sender_profiles', ['is_default'], unique=False)
    op.create_table('outreach_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('sender_profile_id', sa.Integer(), nullable=True),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('message_length', sa.String(length=10), nullable=False),
    sa.Column('follow_up_intervals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sender_profile_id'], ['sender_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_campaigns_created_at'), 'outreach_campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_campaigns_status'), 'outreach_campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_outreach_campaigns_target_id'), 'outreach_campaigns', ['target_id'], unique=False)
    op.create_table('outreach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('decision_maker_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('sender_profile_id', sa.Integer(), nullable=True),
    sa.Column('parent_outreach_id', sa.Integer(), nullable=True),
    sa.Column('follow_up_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('objective', sa.String(length=30), nullable=False),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('message_length', sa.String(length=10), nullable=False),
    sa.Column('to_email', sa.String(length=320), nullable=True),
    sa.Column('to_name', sa.String(length=200), nullable=True),
    sa.Column('cc', sa.String(length=600), nullable=True),
    sa.Column('bcc', sa.String(length=600), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('ai_generated_subject', sa.Text(), nullable=True),
    sa.Column('ai_generated_body', sa.Text(), nullable=True),
    sa.Column('user_edited', sa.Boolean(), nullable=False),
    sa.Column('strategy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('personalization', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('generated_by', sa.String(length=30), nullable=False),
    sa.Column('gmail_draft_id', sa.String(length=120), nullable=True),
    sa.Column('gmail_draft_url', sa.Text(), nullable=True),
    sa.Column('gmail_thread_id', sa.String(length=120), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmail_draft_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_status', sa.String(length=30), nullable=True),
    sa.Column('outcome_reason', sa.String(length=40), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('outcome_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_version_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['outreach_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_maker_id'], ['decision_makers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_outreach_id'], ['outreach.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_profile_id'], ['sender_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_campaign_id'), 'outreach', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_outreach_company_id'), 'outreach', ['company_id'], unique=False)
    op.create_index('ix_outreach_company_status', 'outreach', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_outreach_created_at'), 'outreach', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_decision_maker_id'), 'outreach', ['decision_maker_id'], unique=False)
    op.create_index('ix_outreach_followup_due', 'outreach', ['status', 'next_follow_up_at'], unique=False)
    op.create_index(op.f('ix_outreach_gmail_draft_id'), 'outreach', ['gmail_draft_id'], unique=False)
    op.create_index(op.f('ix_outreach_next_follow_up_at'), 'outreach', ['next_follow_up_at'], unique=False)
    op.create_index(op.f('ix_outreach_opportunity_id'), 'outreach', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_outreach_outcome_status'), 'outreach', ['outcome_status'], unique=False)
    op.create_index(op.f('ix_outreach_owner'), 'outreach', ['owner'], unique=False)
    op.create_index(op.f('ix_outreach_parent_outreach_id'), 'outreach', ['parent_outreach_id'], unique=False)
    op.create_index(op.f('ix_outreach_sent_at'), 'outreach', ['sent_at'], unique=False)
    op.create_index(op.f('ix_outreach_status'), 'outreach', ['status'], unique=False)
    op.create_table('outreach_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outreach_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outreach_id'], ['outreach.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_outcomes_created_at'), 'outreach_outcomes', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_outcomes_outreach_id'), 'outreach_outcomes', ['outreach_id'], unique=False)
    op.create_index(op.f('ix_outreach_outcomes_status'), 'outreach_outcomes', ['status'], unique=False)
    op.create_table('outreach_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outreach_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('generation_method', sa.String(length=30), nullable=False),
    sa.Column('strategy', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('personalization', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outreach_id'], ['outreach.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outreach_id', 'version_number', name='uq_outreach_version_number')
    )
    op.create_index(op.f('ix_outreach_versions_created_at'), 'outreach_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_versions_outreach_id'), 'outreach_versions', ['outreach_id'], unique=False)
    op.create_table('outreach_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outreach_version_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('requires_evidence', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['outreach_version_id'], ['outreach_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_claims_outreach_version_id'), 'outreach_claims', ['outreach_version_id'], unique=False)
    op.create_table('outreach_claim_evidence',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['outreach_claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outreach_claim_evidence')
    op.drop_index(op.f('ix_outreach_claims_outreach_version_id'), table_name='outreach_claims')
    op.drop_table('outreach_claims')
    op.drop_index(op.f('ix_outreach_versions_outreach_id'), table_name='outreach_versions')
    op.drop_index(op.f('ix_outreach_versions_created_at'), table_name='outreach_versions')
    op.drop_table('outreach_versions')
    op.drop_index(op.f('ix_outreach_outcomes_status'), table_name='outreach_outcomes')
    op.drop_index(op.f('ix_outreach_outcomes_outreach_id'), table_name='outreach_outcomes')
    op.drop_index(op.f('ix_outreach_outcomes_created_at'), table_name='outreach_outcomes')
    op.drop_table('outreach_outcomes')
    op.drop_index(op.f('ix_outreach_status'), table_name='outreach')
    op.drop_index(op.f('ix_outreach_sent_at'), table_name='outreach')
    op.drop_index(op.f('ix_outreach_parent_outreach_id'), table_name='outreach')
    op.drop_index(op.f('ix_outreach_owner'), table_name='outreach')
    op.drop_index(op.f('ix_outreach_outcome_status'), table_name='outreach')
    op.drop_index(op.f('ix_outreach_opportunity_id'), table_name='outreach')
    op.drop_index(op.f('ix_outreach_next_follow_up_at'), table_name='outreach')
    op.drop_index(op.f('ix_outreach_gmail_draft_id'), table_name='outreach')
    op.drop_index('ix_outreach_followup_due', table_name='outreach')
    op.drop_index(op.f('ix_outreach_decision_maker_id'), table_name='outreach')
    op.drop_index(op.f('ix_outreach_created_at'), table_name='outreach')
    op.drop_index('ix_outreach_company_status', table_name='outreach')
    op.drop_index(op.f('ix_outreach_company_id'), table_name='outreach')
    op.drop_index(op.f('ix_outreach_campaign_id'), table_name='outreach')
    op.drop_table('outreach')
    op.drop_index(op.f('ix_outreach_campaigns_target_id'), table_name='outreach_campaigns')
    op.drop_index(op.f('ix_outreach_campaigns_status'), table_name='outreach_campaigns')
    op.drop_index(op.f('ix_outreach_campaigns_created_at'), table_name='outreach_campaigns')
    op.drop_table('outreach_campaigns')
    op.drop_index(op.f('ix_sender_profiles_is_default'), table_name='sender_profiles')
    op.drop_index(op.f('ix_sender_profiles_created_at'), table_name='sender_profiles')
    op.drop_table('sender_profiles')
    op.drop_index(op.f('ix_gmail_connections_status'), table_name='gmail_connections')
    op.drop_index(op.f('ix_gmail_connections_is_active'), table_name='gmail_connections')
    op.drop_index(op.f('ix_gmail_connections_created_at'), table_name='gmail_connections')
    op.drop_table('gmail_connections')
    op.drop_index('ix_audit_object', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_object_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_object_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
