"""phase 2: research, evidence, signals, capabilities, opportunities, decision makers

Revision ID: 7c339ba92a9e
Revises: faf59a85d6b1
Create Date: 2026-09-20 10:54:33.373061
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7c339ba92a9e'
down_revision = 'faf59a85d6b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ubm_capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('signal_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rationale_template', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ubm_capabilities_active'), 'ubm_capabilities', ['active'], unique=False)
    op.create_index(op.f('ix_ubm_capabilities_category'), 'ubm_capabilities', ['category'], unique=False)
    op.create_index(op.f('ix_ubm_capabilities_created_at'), 'ubm_capabilities', ['created_at'], unique=False)
    op.create_index(op.f('ix_ubm_capabilities_slug'), 'ubm_capabilities', ['slug'], unique=True)
    op.create_table('research_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sources_discovered', sa.Integer(), nullable=False),
    sa.Column('sources_retrieved', sa.Integer(), nullable=False),
    sa.Column('sources_failed', sa.Integer(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('new_evidence_count', sa.Integer(), nullable=False),
    sa.Column('signals_count', sa.Integer(), nullable=False),
    sa.Column('opportunities_count', sa.Integer(), nullable=False),
    sa.Column('decision_makers_count', sa.Integer(), nullable=False),
    sa.Column('contradictions_count', sa.Integer(), nullable=False),
    sa.Column('search_provider', sa.String(length=50), nullable=True),
    sa.Column('crawler_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_research_runs_company_created', 'research_runs', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_research_runs_company_id'), 'research_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_research_runs_created_at'), 'research_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_runs_status'), 'research_runs', ['status'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('why_relevant', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('confidence_components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('freshness', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('observation_state', sa.String(length=20), nullable=False),
    sa.Column('generated_by', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['ubm_capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fingerprint', name='uq_opportunities_company_fingerprint')
    )
    op.create_index(op.f('ix_opportunities_capability_id'), 'opportunities', ['capability_id'], unique=False)
    op.create_index(op.f('ix_opportunities_company_id'), 'opportunities', ['company_id'], unique=False)
    op.create_index(op.f('ix_opportunities_created_at'), 'opportunities', ['created_at'], unique=False)
    op.create_index(op.f('ix_opportunities_fingerprint'), 'opportunities', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_opportunities_freshness'), 'opportunities', ['freshness'], unique=False)
    op.create_index(op.f('ix_opportunities_research_run_id'), 'opportunities', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('research_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('generated_by', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_run_id')
    )
    op.create_index(op.f('ix_research_briefs_company_id'), 'research_briefs', ['company_id'], unique=False)
    op.create_index(op.f('ix_research_briefs_created_at'), 'research_briefs', ['created_at'], unique=False)
    op.create_table('research_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=True),
    sa.Column('company_page_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('retrieval_status', sa.String(length=20), nullable=False),
    sa.Column('source_reliability', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_page_id'], ['company_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'url', name='uq_research_sources_company_url')
    )
    op.create_index(op.f('ix_research_sources_company_id'), 'research_sources', ['company_id'], unique=False)
    op.create_index('ix_research_sources_company_type', 'research_sources', ['company_id', 'source_type'], unique=False)
    op.create_index(op.f('ix_research_sources_content_hash'), 'research_sources', ['content_hash'], unique=False)
    op.create_index(op.f('ix_research_sources_domain'), 'research_sources', ['domain'], unique=False)
    op.create_index(op.f('ix_research_sources_published_at'), 'research_sources', ['published_at'], unique=False)
    op.create_index(op.f('ix_research_sources_research_run_id'), 'research_sources', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_research_sources_source_type'), 'research_sources', ['source_type'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('freshness', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('confidence_components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('epistemic_status', sa.String(length=20), nullable=False),
    sa.Column('latest_evidence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('observation_state', sa.String(length=20), nullable=False),
    sa.Column('generated_by', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fingerprint', name='uq_signals_company_fingerprint')
    )
    op.create_index(op.f('ix_signals_company_id'), 'signals', ['company_id'], unique=False)
    op.create_index('ix_signals_company_type', 'signals', ['company_id', 'signal_type'], unique=False)
    op.create_index(op.f('ix_signals_created_at'), 'signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_signals_fingerprint'), 'signals', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_signals_freshness'), 'signals', ['freshness'], unique=False)
    op.create_index(op.f('ix_signals_research_run_id'), 'signals', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_table('decision_makers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('role_category', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('observation_state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fingerprint', name='uq_decision_makers_company_fingerprint')
    )
    op.create_index(op.f('ix_decision_makers_company_id'), 'decision_makers', ['company_id'], unique=False)
    op.create_index(op.f('ix_decision_makers_created_at'), 'decision_makers', ['created_at'], unique=False)
    op.create_index(op.f('ix_decision_makers_fingerprint'), 'decision_makers', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_decision_makers_research_run_id'), 'decision_makers', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_decision_makers_role_category'), 'decision_makers', ['role_category'], unique=False)
    op.create_index(op.f('ix_decision_makers_source_id'), 'decision_makers', ['source_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence_type', sa.String(length=40), nullable=False),
    sa.Column('epistemic_status', sa.String(length=20), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=10), nullable=False),
    sa.Column('confidence_components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('extractor', sa.String(length=40), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('first_seen_run_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_run_id', sa.Integer(), nullable=True),
    sa.Column('observation_state', sa.String(length=20), nullable=False),
    sa.Column('times_observed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fingerprint', name='uq_evidence_company_fingerprint')
    )
    op.create_index(op.f('ix_evidence_company_id'), 'evidence', ['company_id'], unique=False)
    op.create_index('ix_evidence_company_published', 'evidence', ['company_id', 'published_at'], unique=False)
    op.create_index('ix_evidence_company_type', 'evidence', ['company_id', 'evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_created_at'), 'evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_fingerprint'), 'evidence', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_evidence_observed_at'), 'evidence', ['observed_at'], unique=False)
    op.create_index(op.f('ix_evidence_published_at'), 'evidence', ['published_at'], unique=False)
    op.create_index(op.f('ix_evidence_research_run_id'), 'evidence', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_id'), 'evidence', ['source_id'], unique=False)
    op.create_table('opportunity_signals',
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_id', 'signal_id')
    )
    op.create_table('contradictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('research_run_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('evidence_a_id', sa.Integer(), nullable=False),
    sa.Column('evidence_b_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('preferred_evidence_id', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_a_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_b_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'evidence_a_id', 'evidence_b_id', name='uq_contradiction_pair')
    )
    op.create_index(op.f('ix_contradictions_company_id'), 'contradictions', ['company_id'], unique=False)
    op.create_index(op.f('ix_contradictions_created_at'), 'contradictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_contradictions_research_run_id'), 'contradictions', ['research_run_id'], unique=False)
    op.create_table('opportunity_evidence',
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_id', 'evidence_id')
    )
    op.create_table('signal_evidence',
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('signal_id', 'evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_evidence')
    op.drop_table('opportunity_evidence')
    op.drop_index(op.f('ix_contradictions_research_run_id'), table_name='contradictions')
    op.drop_index(op.f('ix_contradictions_created_at'), table_name='contradictions')
    op.drop_index(op.f('ix_contradictions_company_id'), table_name='contradictions')
    op.drop_table('contradictions')
    op.drop_table('opportunity_signals')
    op.drop_index(op.f('ix_evidence_source_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_research_run_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_published_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_observed_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_fingerprint'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_created_at'), table_name='evidence')
    op.drop_index('ix_evidence_company_type', table_name='evidence')
    op.drop_index('ix_evidence_company_published', table_name='evidence')
    op.drop_index(op.f('ix_evidence_company_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_decision_makers_source_id'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_role_category'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_research_run_id'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_fingerprint'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_created_at'), table_name='decision_makers')
    op.drop_index(op.f('ix_decision_makers_company_id'), table_name='decision_makers')
    op.drop_table('decision_makers')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_research_run_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_freshness'), table_name='signals')
    op.drop_index(op.f('ix_signals_fingerprint'), table_name='signals')
    op.drop_index(op.f('ix_signals_created_at'), table_name='signals')
    op.drop_index('ix_signals_company_type', table_name='signals')
    op.drop_index(op.f('ix_signals_company_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_research_sources_source_type'), table_name='research_sources')
    op.drop_index(op.f('ix_research_sources_research_run_id'), table_name='research_sources')
    op.drop_index(op.f('ix_research_sources_published_at'), table_name='research_sources')
    op.drop_index(op.f('ix_research_sources_domain'), table_name='research_sources')
    op.drop_index(op.f('ix_research_sources_content_hash'), table_name='research_sources')
    op.drop_index('ix_research_sources_company_type', table_name='research_sources')
    op.drop_index(op.f('ix_research_sources_company_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_research_briefs_created_at'), table_name='research_briefs')
    op.drop_index(op.f('ix_research_briefs_company_id'), table_name='research_briefs')
    op.drop_table('research_briefs')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_research_run_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_freshness'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_fingerprint'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_created_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_company_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_capability_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_research_runs_status'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_created_at'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_company_id'), table_name='research_runs')
    op.drop_index('ix_research_runs_company_created', table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_ubm_capabilities_slug'), table_name='ubm_capabilities')
    op.drop_index(op.f('ix_ubm_capabilities_created_at'), table_name='ubm_capabilities')
    op.drop_index(op.f('ix_ubm_capabilities_category'), table_name='ubm_capabilities')
    op.drop_index(op.f('ix_ubm_capabilities_active'), table_name='ubm_capabilities')
    op.drop_table('ubm_capabilities')
    # ### end Alembic commands ###
