"""initial schema

Revision ID: faf59a85d6b1
Revises: 
Create Date: 2026-09-19 22:50:50.601323
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'faf59a85d6b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('search_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_created_at'), 'targets', ['created_at'], unique=False)
    op.create_index('ix_targets_industry_location', 'targets', ['industry', 'location'], unique=False)
    op.create_table('discovery_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queries_count', sa.Integer(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('unique_domains_count', sa.Integer(), nullable=False),
    sa.Column('new_companies_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_companies_count', sa.Integer(), nullable=False),
    sa.Column('rejected_results_count', sa.Integer(), nullable=False),
    sa.Column('failed_queries_count', sa.Integer(), nullable=False),
    sa.Column('search_provider', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_runs_created_at'), 'discovery_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_discovery_runs_status'), 'discovery_runs', ['status'], unique=False)
    op.create_index(op.f('ix_discovery_runs_target_id'), 'discovery_runs', ['target_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('canonical_domain', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('crawl_error', sa.Text(), nullable=True),
    sa.Column('first_discovery_run_id', sa.Integer(), nullable=True),
    sa.Column('last_researched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['first_discovery_run_id'], ['discovery_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_canonical_domain'), 'companies', ['canonical_domain'], unique=True)
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_first_discovery_run_id'), 'companies', ['first_discovery_run_id'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_location'), 'companies', ['location'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_status'), 'companies', ['status'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discovery_run_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('template', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['discovery_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_discovery_run_id'), 'search_queries', ['discovery_run_id'], unique=False)
    op.create_table('company_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('page_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'url', name='uq_company_pages_company_url')
    )
    op.create_index(op.f('ix_company_pages_company_id'), 'company_pages', ['company_id'], unique=False)
    op.create_index('ix_company_pages_company_type', 'company_pages', ['company_id', 'page_type'], unique=False)
    op.create_table('search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_query_id', sa.Integer(), nullable=False),
    sa.Column('discovery_run_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('source_engine', sa.String(length=100), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('extracted_domain', sa.String(length=255), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=100), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['discovery_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_results_discovery_run_id'), 'search_results', ['discovery_run_id'], unique=False)
    op.create_index(op.f('ix_search_results_extracted_domain'), 'search_results', ['extracted_domain'], unique=False)
    op.create_index('ix_search_results_run_domain', 'search_results', ['discovery_run_id', 'extracted_domain'], unique=False)
    op.create_index(op.f('ix_search_results_search_query_id'), 'search_results', ['search_query_id'], unique=False)
    op.create_table('company_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('discovery_run_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('search_result_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_engine', sa.String(length=100), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discovery_run_id'], ['discovery_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['search_result_id'], ['search_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'url', name='uq_company_sources_company_url')
    )
    op.create_index(op.f('ix_company_sources_company_id'), 'company_sources', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_sources_discovered_at'), 'company_sources', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_company_sources_discovery_run_id'), 'company_sources', ['discovery_run_id'], unique=False)
    op.create_index(op.f('ix_company_sources_target_id'), 'company_sources', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_sources_target_id'), table_name='company_sources')
    op.drop_index(op.f('ix_company_sources_discovery_run_id'), table_name='company_sources')
    op.drop_index(op.f('ix_company_sources_discovered_at'), table_name='company_sources')
    op.drop_index(op.f('ix_company_sources_company_id'), table_name='company_sources')
    op.drop_table('company_sources')
    op.drop_index(op.f('ix_search_results_search_query_id'), table_name='search_results')
    op.drop_index('ix_search_results_run_domain', table_name='search_results')
    op.drop_index(op.f('ix_search_results_extracted_domain'), table_name='search_results')
    op.drop_index(op.f('ix_search_results_discovery_run_id'), table_name='search_results')
    op.drop_table('search_results')
    op.drop_index('ix_company_pages_company_type', table_name='company_pages')
    op.drop_index(op.f('ix_company_pages_company_id'), table_name='company_pages')
    op.drop_table('company_pages')
    op.drop_index(op.f('ix_search_queries_discovery_run_id'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_companies_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_location'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_first_discovery_run_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_index(op.f('ix_companies_canonical_domain'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_discovery_runs_target_id'), table_name='discovery_runs')
    op.drop_index(op.f('ix_discovery_runs_status'), table_name='discovery_runs')
    op.drop_index(op.f('ix_discovery_runs_created_at'), table_name='discovery_runs')
    op.drop_table('discovery_runs')
    op.drop_index('ix_targets_industry_location', table_name='targets')
    op.drop_index(op.f('ix_targets_created_at'), table_name='targets')
    op.drop_table('targets')
    # ### end Alembic commands ###
